---
- name: Ensure Helm is installed
  hosts: observer
  become: true

  tasks:
    - name: Check if Helm is already installed
      ansible.builtin.command: which helm
      register: helm_check
      changed_when: false
      failed_when: false
      check_mode: false

    - name: Download Helm install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'
      when: helm_check.rc != 0

    - name: Run Helm install script
      ansible.builtin.command: /tmp/get_helm.sh
      when: helm_check.rc != 0

    - name: Confirm Helm version
      ansible.builtin.command: helm version
      register: helm_version
      changed_when: false
      check_mode: false

    - name: Show Helm version
      ansible.builtin.debug:
        var: helm_version.stdout
